#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download SAS documentation PDFs from a JSONL manifest."
    )
    parser.add_argument(
        "--manifest",
        default="data/manifests/sas-docs.jsonl",
        help="JSONL manifest generated by prepare_sas_rag_sources.py",
    )
    parser.add_argument(
        "--output-dir",
        default="data/raw/sas-pdfs",
        help="Directory where downloaded PDFs will be stored.",
    )
    parser.add_argument(
        "--metadata-output",
        default="data/raw/sas-pdfs/downloaded.jsonl",
        help="JSONL file describing downloaded PDFs.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-download PDFs even if the local file already exists.",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Pass -k to curl to skip TLS certificate verification.",
    )
    parser.add_argument(
        "--connect-timeout",
        type=int,
        default=20,
        help="curl connect timeout in seconds.",
    )
    parser.add_argument(
        "--max-time",
        type=int,
        default=1800,
        help="curl max transfer time in seconds.",
    )
    return parser.parse_args()


def load_manifest(manifest_path: Path) -> list[dict[str, object]]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")

    records: list[dict[str, object]] = []
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        records.append(json.loads(line))
    return records


def download_pdf(
    record: dict[str, object],
    output_root: Path,
    force: bool,
    insecure: bool,
    connect_timeout: int,
    max_time: int,
) -> dict[str, object]:
    cdc_id = str(record["cdc_id"])
    version = str(record["version"])
    locale = str(record["locale"])
    docset = str(record["docset"])
    pdf_url = str(record["pdf_url"])

    target_path = output_root / cdc_id / version / locale / f"{docset}.pdf"
    target_path.parent.mkdir(parents=True, exist_ok=True)

    if target_path.exists() and target_path.stat().st_size > 0 and not force:
        status = "skipped"
    else:
        command = [
            "curl",
            "-fL",
            "--retry",
            "3",
            "--connect-timeout",
            str(connect_timeout),
            "--max-time",
            str(max_time),
            pdf_url,
            "-o",
            str(target_path),
        ]
        if insecure:
            command.insert(1, "-k")

        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(
                f"Failed to download {pdf_url}\n"
                f"stdout:\n{result.stdout}\n"
                f"stderr:\n{result.stderr}"
            )
        status = "downloaded"

    return {
        "name": record["name"],
        "html_url": record["html_url"],
        "pdf_url": pdf_url,
        "cdc_id": cdc_id,
        "version": version,
        "locale": locale,
        "docset": docset,
        "local_path": str(target_path),
        "bytes": target_path.stat().st_size,
        "status": status,
    }


def write_metadata(records: list[dict[str, object]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def main() -> int:
    args = parse_args()

    try:
        manifest_records = load_manifest(Path(args.manifest))
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    downloaded: list[dict[str, object]] = []
    for record in manifest_records:
        try:
            item = download_pdf(
                record=record,
                output_root=Path(args.output_dir),
                force=args.force,
                insecure=args.insecure,
                connect_timeout=args.connect_timeout,
                max_time=args.max_time,
            )
        except RuntimeError as exc:
            print(str(exc), file=sys.stderr)
            return 1

        downloaded.append(item)
        print(
            f"{item['status']}: {item['docset']} -> {item['local_path']} "
            f"({item['bytes']} bytes)"
        )

    write_metadata(downloaded, Path(args.metadata_output))
    print(f"Wrote metadata for {len(downloaded)} PDFs to {args.metadata_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
